name: Build A.

on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sleep 10
          echo "Build A"
