name: Deploy A.

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    runs-on: ubuntu-20.04
    environment: production
    steps:
      - run: gh release create $(date +'%Y%m%d%H%M%S')
  build:
    uses: ./.github/workflows/build_a.yml
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    env:
      NAME: ${{ vars.HOGE }}
    needs:
      - build
    steps:
      - run: echo "Deploy A ${{ env.NAME }}"
