name: Deploy A.

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production
    uses: kosnu/learning_github/.github/workflows/build_a.yml@main
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    needs:
      - build
    steps:
      - run: echo "Deploy A ${{ vars.HOGE }}"
