name: Deploy A.

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    runs-on: ubuntu-20.04
    environment: production
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: gh release create $(date +'%Y%m%d%H%M%S') -n test
  build:
    uses: ./.github/workflows/build_a.yml
  deploy:
    runs-on: ubuntu-20.04
    environment: production
    env:
      NAME: ${{ vars.HOGE }}
    needs:
      - build
    steps:
      - run: echo "Deploy A ${{ env.NAME }}"
