on:
  workflow_dispatch:
  push:
    branches:
      - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          sleep 10
          echo "Build B"
  deploy:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - run: echo "Deploy A"
